services:
  auth:
    build:
      context: .
      dockerfile: ./cmd/auth/Dockerfile
    container_name: auth
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
      - POSTGRES_HOST=${AUTH_POSTGRES_HOST}
      - POSTGRES_PORT=${AUTH_POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5051
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - REDIS_ADDR=${REDIS_ADDR}
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./logs:/out/logs
      - ./certs:/certs:ro
    ports:
      - "5051:5051"
    restart: always
    depends_on:
      - auth-postgres
      - finance-redis

  users:
    build:
      context: .
      dockerfile: ./cmd/users/Dockerfile
    container_name: users
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${USERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USERS_POSTGRES_DB}
      - POSTGRES_HOST=${USERS_POSTGRES_HOST}
      - POSTGRES_PORT=${USERS_POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5052
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./logs:/out/logs
      - ./certs:/certs:ro
    ports:
      - "5052:5052"
    restart: always
    depends_on:
      - users-postgres

  admin:
    build:
      context: .
      dockerfile: ./cmd/admin/Dockerfile
    container_name: admin
    networks:
      - finance-net
    environment:
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5053
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - REDIS_ADDR=${REDIS_ADDR}
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./logs:/out/logs
      - ./certs:/certs:ro
    ports:
      - "5053:5053"
    restart: always
    depends_on:
      - finance-redis
      - kafka

  finance:
    build:
      context: .
      dockerfile: ./cmd/finance/Dockerfile
    container_name: finance
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${FINANCE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FINANCE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FINANCE_POSTGRES_DB}
      - POSTGRES_HOST=${FINANCE_POSTGRES_HOST}
      - POSTGRES_PORT=${FINANCE_POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5050
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./logs:/out/logs
      - ./certs:/certs:ro
    ports:
      - "5050:5050"
    restart: always
    depends_on:
      - finance-postgres
      - finance-redis
      - kafka

  currency:
    build:
      context: .
      dockerfile: ./cmd/currency/Dockerfile
    container_name: currency
    networks:
      - finance-net
    environment:
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5055
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - REDIS_ADDR=${REDIS_ADDR}
      - KAFKA_BROKERS=${KAFKA_BROKERS}
      - CURRENCY_API_URL=https://api.frankfurter.app/latest
      - CURRENCY_CACHE_TTL=1h
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./logs:/out/logs
      - ./certs:/certs:ro
    ports:
      - "5055:5055"
    restart: always
    depends_on:
      - finance-redis
      - kafka

  gateway:
    build:
      context: .
      dockerfile: ./cmd/gateway/Dockerfile
    container_name: gateway
    networks:
      - finance-net
    environment:
      - ADDRESS=:8081
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - LEVEL=${LOGGER_LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
      - TIME_ZONE=${TIME_ZONE}
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_CERT_FILE=${TLS_CERT_FILE}
      - TLS_KEY_FILE=${TLS_KEY_FILE}
      - TLS_CA_FILE=${TLS_CA_FILE}
    volumes:
      - ./certs:/certs:ro
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - auth
      - users
      - admin
      - finance

  finance-postgres:
    image: postgres:15-alpine
    container_name: finance-env-postgres
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${FINANCE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FINANCE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FINANCE_POSTGRES_DB}
    volumes:
      - ./out/pgdata/finance:/var/lib/postgresql/data:rw
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${FINANCE_POSTGRES_USER} -d ${FINANCE_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  finance-postgres-migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - finance-net
    depends_on:
      finance-postgres:
        condition: service_started
    environment:
      - POSTGRES_USER=${FINANCE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${FINANCE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${FINANCE_POSTGRES_DB}
    command: -path /migrations -database "postgres://${FINANCE_POSTGRES_USER}:${FINANCE_POSTGRES_PASSWORD}@finance-postgres:5432/${FINANCE_POSTGRES_DB}?sslmode=disable" up

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: finance-postgres-port-forwarder
    networks:
      - finance-net
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:finance-postgres:5432
    ports:
      - "127.0.0.1:5435:5432"

  auth-postgres:
    image: postgres:15-alpine
    container_name: auth-env-postgres
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
    volumes:
      - ./out/pgdata/auth:/var/lib/postgresql/data:rw
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-postgres-migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - finance-net
    depends_on:
      - auth-postgres
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}
    command: -path /migrations -database "postgres://${AUTH_POSTGRES_USER}:${AUTH_POSTGRES_PASSWORD}@auth-postgres:5432/${AUTH_POSTGRES_DB}?sslmode=disable" up

  auth-port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: auth-port-forwarder
    networks:
      - finance-net
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:auth-postgres:5432
    ports:
      - "127.0.0.1:5433:5432"

  users-postgres:
    image: postgres:15-alpine
    container_name: users-env-postgres
    networks:
      - finance-net
    environment:
      - POSTGRES_USER=${USERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USERS_POSTGRES_DB}
    volumes:
      - ./out/pgdata/users:/var/lib/postgresql/data:rw
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USERS_POSTGRES_USER} -d ${USERS_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  users-postgres-migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    networks:
      - finance-net
    depends_on:
      - users-postgres
    environment:
      - POSTGRES_USER=${USERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USERS_POSTGRES_DB}
    command: -path /migrations -database "postgres://${USERS_POSTGRES_USER}:${USERS_POSTGRES_PASSWORD}@users-postgres:5432/${USERS_POSTGRES_DB}?sslmode=disable" up

  users-port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: users-port-forwarder
    networks:
      - finance-net
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:users-postgres:5432
    ports:
      - "127.0.0.1:5434:5432"

  swagger:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.26.4-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - .:/code
    networks:
      - finance-net

  finance-redis:
    image: redis:7-alpine
    container_name: finance-redis
    networks:
      - finance-net
    ports:
      - "6379:6379"
    volumes:
      - ./out/redisdata:/data
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5



  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: finance-kafka
    networks:
      - finance-net
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: finance-kafka-ui
    networks:
      - finance-net
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: finance-jaeger
    networks:
      - finance-net
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
    restart: unless-stopped
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: finance-prometheus
    networks:
      - finance-net
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./out/prometheus:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'


networks:
  finance-net:
    driver: bridge