services:
  finance:
    build:
      context: .
      dockerfile: ./cmd/finance/Dockerfile
    container_name: finance
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=finance-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
      - LEVEL={LEVEL}
      - LOGGER_FOLDER=${LOGGER_FOLDER}
      - ADDRESS=:5050
      - SHUTDOWN_TIMEOUT=${SHUTDOWN_TIMEOUT}
      - TIME_ZONE=${TIME_ZONE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_DURATION=${JWT_DURATION}
    volumes:
      - ./logs:/out/logs
    ports:
      - "5050:5050"
    restart: always


  finance-postgres:
    image: postgres:15-alpine
    container_name: finance-env-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./out/pgdata:/var/lib/postgresql/data:rw
    restart: always

  finance-postgres-migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      - finance-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: finance-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:finance-postgres:5432
    ports:
      - "127.0.0.1:5433:5432"

  swagger:
    build:
      context: .
      dockerfile_inline: |
        FROM golang:1.26.4-alpine
        RUN apk add --no-cache git
        RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
        WORKDIR /code
        ENTRYPOINT ["swag"]
    volumes:
      - .:/code

  
