// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "backend/internal/core/domain"
	pool "backend/internal/core/repository/postgres/pool"
	context "context"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockFinanceRepository is a mock of FinanceRepository interface.
type MockFinanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFinanceRepositoryMockRecorder
}

// MockFinanceRepositoryMockRecorder is the mock recorder for MockFinanceRepository.
type MockFinanceRepositoryMockRecorder struct {
	mock *MockFinanceRepository
}

// NewMockFinanceRepository creates a new mock instance.
func NewMockFinanceRepository(ctrl *gomock.Controller) *MockFinanceRepository {
	mock := &MockFinanceRepository{ctrl: ctrl}
	mock.recorder = &MockFinanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFinanceRepository) EXPECT() *MockFinanceRepositoryMockRecorder {
	return m.recorder
}

// CreateTransactionTx mocks base method.
func (m *MockFinanceRepository) CreateTransactionTx(ctx context.Context, tx pool.Tx, transaction domain.Finance) (domain.Finance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionTx", ctx, tx, transaction)
	ret0, _ := ret[0].(domain.Finance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransactionTx indicates an expected call of CreateTransactionTx.
func (mr *MockFinanceRepositoryMockRecorder) CreateTransactionTx(ctx, tx, transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionTx", reflect.TypeOf((*MockFinanceRepository)(nil).CreateTransactionTx), ctx, tx, transaction)
}

// DeleteTransaction mocks base method.
func (m *MockFinanceRepository) DeleteTransaction(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockFinanceRepositoryMockRecorder) DeleteTransaction(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockFinanceRepository)(nil).DeleteTransaction), ctx, id)
}

// GetCategories mocks base method.
func (m *MockFinanceRepository) GetCategories(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockFinanceRepositoryMockRecorder) GetCategories(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockFinanceRepository)(nil).GetCategories), ctx, userID)
}

// GetDashboard mocks base method.
func (m *MockFinanceRepository) GetDashboard(ctx context.Context, userID int) (domain.Dashboard, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboard", ctx, userID)
	ret0, _ := ret[0].(domain.Dashboard)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboard indicates an expected call of GetDashboard.
func (mr *MockFinanceRepositoryMockRecorder) GetDashboard(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboard", reflect.TypeOf((*MockFinanceRepository)(nil).GetDashboard), ctx, userID)
}

// GetTransaction mocks base method.
func (m *MockFinanceRepository) GetTransaction(ctx context.Context, id int) (domain.Finance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", ctx, id)
	ret0, _ := ret[0].(domain.Finance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockFinanceRepositoryMockRecorder) GetTransaction(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockFinanceRepository)(nil).GetTransaction), ctx, id)
}

// GetTransactions mocks base method.
func (m *MockFinanceRepository) GetTransactions(ctx context.Context, userID int, transactionType, category *string, from, to *time.Time, limit, offset int) ([]domain.Finance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactions", ctx, userID, transactionType, category, from, to, limit, offset)
	ret0, _ := ret[0].([]domain.Finance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactions indicates an expected call of GetTransactions.
func (mr *MockFinanceRepositoryMockRecorder) GetTransactions(ctx, userID, transactionType, category, from, to, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactions", reflect.TypeOf((*MockFinanceRepository)(nil).GetTransactions), ctx, userID, transactionType, category, from, to, limit, offset)
}

// UpdateTransaction mocks base method.
func (m *MockFinanceRepository) UpdateTransaction(ctx context.Context, transaction domain.Finance) (domain.Finance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", ctx, transaction)
	ret0, _ := ret[0].(domain.Finance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockFinanceRepositoryMockRecorder) UpdateTransaction(ctx, transaction interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockFinanceRepository)(nil).UpdateTransaction), ctx, transaction)
}
