// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: finance/finance.proto

package gRPC

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_finance_finance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{0}
}

type GetCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesRequest) Reset() {
	*x = GetCategoriesRequest{}
	mi := &file_finance_finance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesRequest) ProtoMessage() {}

func (x *GetCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesRequest.ProtoReflect.Descriptor instead.
func (*GetCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{1}
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_finance_finance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *string                `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	Category      *string                `protobuf:"bytes,2,opt,name=category,proto3,oneof" json:"category,omitempty"`
	From          *string                `protobuf:"bytes,3,opt,name=from,proto3,oneof" json:"from,omitempty"`
	To            *string                `protobuf:"bytes,4,opt,name=to,proto3,oneof" json:"to,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_finance_finance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionsRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

func (x *GetTransactionsRequest) GetCategory() string {
	if x != nil && x.Category != nil {
		return *x.Category
	}
	return ""
}

func (x *GetTransactionsRequest) GetFrom() string {
	if x != nil && x.From != nil {
		return *x.From
	}
	return ""
}

func (x *GetTransactionsRequest) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *GetTransactionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TypeTransaction string                 `protobuf:"bytes,1,opt,name=type_transaction,json=typeTransaction,proto3" json:"type_transaction,omitempty"`
	Amount          float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category        string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_finance_finance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTransactionRequest) GetTypeTransaction() string {
	if x != nil {
		return x.TypeTransaction
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeTransaction string                 `protobuf:"bytes,2,opt,name=type_transaction,json=typeTransaction,proto3" json:"type_transaction,omitempty"`
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category        string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_finance_finance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTransactionRequest) GetTypeTransaction() string {
	if x != nil {
		return x.TypeTransaction
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_finance_finance_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransactionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type TransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Version         int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	TypeTransaction string                 `protobuf:"bytes,3,opt,name=type_transaction,json=typeTransaction,proto3" json:"type_transaction,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Category        string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UserId          int32                  `protobuf:"varint,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_finance_finance_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{7}
}

func (x *TransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TransactionResponse) GetTypeTransaction() string {
	if x != nil {
		return x.TypeTransaction
	}
	return ""
}

func (x *TransactionResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TransactionResponse) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionResponse `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_finance_finance_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionsResponse) GetTransactions() []*TransactionResponse {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *GetTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetTransactionsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTransactionsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type DashboardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalBalance       float64                `protobuf:"fixed64,1,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	MonthlyIncome      float64                `protobuf:"fixed64,2,opt,name=monthly_income,json=monthlyIncome,proto3" json:"monthly_income,omitempty"`
	MonthlyExpenses    float64                `protobuf:"fixed64,3,opt,name=monthly_expenses,json=monthlyExpenses,proto3" json:"monthly_expenses,omitempty"`
	SavingsRate        float64                `protobuf:"fixed64,4,opt,name=savings_rate,json=savingsRate,proto3" json:"savings_rate,omitempty"`
	DailyStats         []*DailyStat           `protobuf:"bytes,5,rep,name=daily_stats,json=dailyStats,proto3" json:"daily_stats,omitempty"`
	RecentTransactions []*RecentTransaction   `protobuf:"bytes,6,rep,name=recent_transactions,json=recentTransactions,proto3" json:"recent_transactions,omitempty"`
	TopCategories      []*CategoryStat        `protobuf:"bytes,7,rep,name=top_categories,json=topCategories,proto3" json:"top_categories,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DashboardResponse) Reset() {
	*x = DashboardResponse{}
	mi := &file_finance_finance_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardResponse) ProtoMessage() {}

func (x *DashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardResponse.ProtoReflect.Descriptor instead.
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{9}
}

func (x *DashboardResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *DashboardResponse) GetMonthlyIncome() float64 {
	if x != nil {
		return x.MonthlyIncome
	}
	return 0
}

func (x *DashboardResponse) GetMonthlyExpenses() float64 {
	if x != nil {
		return x.MonthlyExpenses
	}
	return 0
}

func (x *DashboardResponse) GetSavingsRate() float64 {
	if x != nil {
		return x.SavingsRate
	}
	return 0
}

func (x *DashboardResponse) GetDailyStats() []*DailyStat {
	if x != nil {
		return x.DailyStats
	}
	return nil
}

func (x *DashboardResponse) GetRecentTransactions() []*RecentTransaction {
	if x != nil {
		return x.RecentTransactions
	}
	return nil
}

func (x *DashboardResponse) GetTopCategories() []*CategoryStat {
	if x != nil {
		return x.TopCategories
	}
	return nil
}

type DailyStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Income        float64                `protobuf:"fixed64,2,opt,name=income,proto3" json:"income,omitempty"`
	Expense       float64                `protobuf:"fixed64,3,opt,name=expense,proto3" json:"expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyStat) Reset() {
	*x = DailyStat{}
	mi := &file_finance_finance_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyStat) ProtoMessage() {}

func (x *DailyStat) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyStat.ProtoReflect.Descriptor instead.
func (*DailyStat) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{10}
}

func (x *DailyStat) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyStat) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *DailyStat) GetExpense() float64 {
	if x != nil {
		return x.Expense
	}
	return 0
}

type RecentTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTransaction) Reset() {
	*x = RecentTransaction{}
	mi := &file_finance_finance_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTransaction) ProtoMessage() {}

func (x *RecentTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTransaction.ProtoReflect.Descriptor instead.
func (*RecentTransaction) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{11}
}

func (x *RecentTransaction) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecentTransaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecentTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RecentTransaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecentTransaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CategoryStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryStat) Reset() {
	*x = CategoryStat{}
	mi := &file_finance_finance_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryStat) ProtoMessage() {}

func (x *CategoryStat) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryStat.ProtoReflect.Descriptor instead.
func (*CategoryStat) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{12}
}

func (x *CategoryStat) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CategoryStat) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryStat) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type GetCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []string               `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoriesResponse) Reset() {
	*x = GetCategoriesResponse{}
	mi := &file_finance_finance_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoriesResponse) ProtoMessage() {}

func (x *GetCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_finance_finance_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoriesResponse.ProtoReflect.Descriptor instead.
func (*GetCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_finance_finance_proto_rawDescGZIP(), []int{13}
}

func (x *GetCategoriesResponse) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_finance_finance_proto protoreflect.FileDescriptor

const file_finance_finance_proto_rawDesc = "" +
	"\n" +
	"\x15finance/finance.proto\x12\afinance\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n" +
	"\x13GetDashboardRequest\"\x16\n" +
	"\x14GetCategoriesRequest\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xd4\x01\n" +
	"\x16GetTransactionsRequest\x12\x17\n" +
	"\x04type\x18\x01 \x01(\tH\x00R\x04type\x88\x01\x01\x12\x1f\n" +
	"\bcategory\x18\x02 \x01(\tH\x01R\bcategory\x88\x01\x01\x12\x17\n" +
	"\x04from\x18\x03 \x01(\tH\x02R\x04from\x88\x01\x01\x12\x13\n" +
	"\x02to\x18\x04 \x01(\tH\x03R\x02to\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offsetB\a\n" +
	"\x05_typeB\v\n" +
	"\t_categoryB\a\n" +
	"\x05_fromB\x05\n" +
	"\x03_to\"y\n" +
	"\x18CreateTransactionRequest\x12)\n" +
	"\x10type_transaction\x18\x01 \x01(\tR\x0ftypeTransaction\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\"\x89\x01\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12)\n" +
	"\x10type_transaction\x18\x02 \x01(\tR\x0ftypeTransaction\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xf2\x01\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12)\n" +
	"\x10type_transaction\x18\x03 \x01(\tR\x0ftypeTransaction\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\auser_id\x18\a \x01(\x05R\x06userId\"\x9f\x01\n" +
	"\x17GetTransactionsResponse\x12@\n" +
	"\ftransactions\x18\x01 \x03(\v2\x1c.finance.TransactionResponseR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"\xed\x02\n" +
	"\x11DashboardResponse\x12#\n" +
	"\rtotal_balance\x18\x01 \x01(\x01R\ftotalBalance\x12%\n" +
	"\x0emonthly_income\x18\x02 \x01(\x01R\rmonthlyIncome\x12)\n" +
	"\x10monthly_expenses\x18\x03 \x01(\x01R\x0fmonthlyExpenses\x12!\n" +
	"\fsavings_rate\x18\x04 \x01(\x01R\vsavingsRate\x123\n" +
	"\vdaily_stats\x18\x05 \x03(\v2\x12.finance.DailyStatR\n" +
	"dailyStats\x12K\n" +
	"\x13recent_transactions\x18\x06 \x03(\v2\x1a.finance.RecentTransactionR\x12recentTransactions\x12<\n" +
	"\x0etop_categories\x18\a \x03(\v2\x15.finance.CategoryStatR\rtopCategories\"Q\n" +
	"\tDailyStat\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x01R\x06income\x12\x18\n" +
	"\aexpense\x18\x03 \x01(\x01R\aexpense\"\xa6\x01\n" +
	"\x11RecentTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\fCategoryStat\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"7\n" +
	"\x15GetCategoriesResponse\x12\x1e\n" +
	"\n" +
	"categories\x18\x01 \x03(\tR\n" +
	"categories2\xe3\x06\n" +
	"\x0eFinanceService\x12k\n" +
	"\fGetDashboard\x12\x1c.finance.GetDashboardRequest\x1a\x1a.finance.DashboardResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/finance/dashboard\x12r\n" +
	"\rGetCategories\x12\x1d.finance.GetCategoriesRequest\x1a\x1e.finance.GetCategoriesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/finance/categories\x12|\n" +
	"\x11CreateTransaction\x12!.finance.CreateTransactionRequest\x1a\x1c.finance.TransactionResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/finance/transaction\x12z\n" +
	"\x0fGetTransactions\x12\x1f.finance.GetTransactionsRequest\x1a .finance.GetTransactionsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/finance/transactions\x12x\n" +
	"\x0eGetTransaction\x12\x1e.finance.GetTransactionRequest\x1a\x1c.finance.TransactionResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/finance/transaction/{id}\x12\x81\x01\n" +
	"\x11UpdateTransaction\x12!.finance.UpdateTransactionRequest\x1a\x1c.finance.TransactionResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\x1a /api/v1/finance/transaction/{id}\x12x\n" +
	"\x11DeleteTransaction\x12!.finance.DeleteTransactionRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\"* /api/v1/finance/transaction/{id}B\vZ\t./financeb\x06proto3"

var (
	file_finance_finance_proto_rawDescOnce sync.Once
	file_finance_finance_proto_rawDescData []byte
)

func file_finance_finance_proto_rawDescGZIP() []byte {
	file_finance_finance_proto_rawDescOnce.Do(func() {
		file_finance_finance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_finance_finance_proto_rawDesc), len(file_finance_finance_proto_rawDesc)))
	})
	return file_finance_finance_proto_rawDescData
}

var file_finance_finance_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_finance_finance_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),      // 0: finance.GetDashboardRequest
	(*GetCategoriesRequest)(nil),     // 1: finance.GetCategoriesRequest
	(*GetTransactionRequest)(nil),    // 2: finance.GetTransactionRequest
	(*GetTransactionsRequest)(nil),   // 3: finance.GetTransactionsRequest
	(*CreateTransactionRequest)(nil), // 4: finance.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil), // 5: finance.UpdateTransactionRequest
	(*DeleteTransactionRequest)(nil), // 6: finance.DeleteTransactionRequest
	(*TransactionResponse)(nil),      // 7: finance.TransactionResponse
	(*GetTransactionsResponse)(nil),  // 8: finance.GetTransactionsResponse
	(*DashboardResponse)(nil),        // 9: finance.DashboardResponse
	(*DailyStat)(nil),                // 10: finance.DailyStat
	(*RecentTransaction)(nil),        // 11: finance.RecentTransaction
	(*CategoryStat)(nil),             // 12: finance.CategoryStat
	(*GetCategoriesResponse)(nil),    // 13: finance.GetCategoriesResponse
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
}
var file_finance_finance_proto_depIdxs = []int32{
	14, // 0: finance.TransactionResponse.created_at:type_name -> google.protobuf.Timestamp
	7,  // 1: finance.GetTransactionsResponse.transactions:type_name -> finance.TransactionResponse
	10, // 2: finance.DashboardResponse.daily_stats:type_name -> finance.DailyStat
	11, // 3: finance.DashboardResponse.recent_transactions:type_name -> finance.RecentTransaction
	12, // 4: finance.DashboardResponse.top_categories:type_name -> finance.CategoryStat
	14, // 5: finance.RecentTransaction.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: finance.FinanceService.GetDashboard:input_type -> finance.GetDashboardRequest
	1,  // 7: finance.FinanceService.GetCategories:input_type -> finance.GetCategoriesRequest
	4,  // 8: finance.FinanceService.CreateTransaction:input_type -> finance.CreateTransactionRequest
	3,  // 9: finance.FinanceService.GetTransactions:input_type -> finance.GetTransactionsRequest
	2,  // 10: finance.FinanceService.GetTransaction:input_type -> finance.GetTransactionRequest
	5,  // 11: finance.FinanceService.UpdateTransaction:input_type -> finance.UpdateTransactionRequest
	6,  // 12: finance.FinanceService.DeleteTransaction:input_type -> finance.DeleteTransactionRequest
	9,  // 13: finance.FinanceService.GetDashboard:output_type -> finance.DashboardResponse
	13, // 14: finance.FinanceService.GetCategories:output_type -> finance.GetCategoriesResponse
	7,  // 15: finance.FinanceService.CreateTransaction:output_type -> finance.TransactionResponse
	8,  // 16: finance.FinanceService.GetTransactions:output_type -> finance.GetTransactionsResponse
	7,  // 17: finance.FinanceService.GetTransaction:output_type -> finance.TransactionResponse
	7,  // 18: finance.FinanceService.UpdateTransaction:output_type -> finance.TransactionResponse
	15, // 19: finance.FinanceService.DeleteTransaction:output_type -> google.protobuf.Empty
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_finance_finance_proto_init() }
func file_finance_finance_proto_init() {
	if File_finance_finance_proto != nil {
		return
	}
	file_finance_finance_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_finance_finance_proto_rawDesc), len(file_finance_finance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_finance_finance_proto_goTypes,
		DependencyIndexes: file_finance_finance_proto_depIdxs,
		MessageInfos:      file_finance_finance_proto_msgTypes,
	}.Build()
	File_finance_finance_proto = out.File
	file_finance_finance_proto_goTypes = nil
	file_finance_finance_proto_depIdxs = nil
}
