// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/currency/currency.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *GetRatesRequest) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

type GetRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          string                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Rates         map[string]float64     `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResponse) Reset() {
	*x = GetRatesResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResponse) ProtoMessage() {}

func (x *GetRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResponse.ProtoReflect.Descriptor instead.
func (*GetRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetRatesResponse) GetBase() string {
	if x != nil {
		return x.Base
	}
	return ""
}

func (x *GetRatesResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *GetRatesResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ConvertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *ConvertRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ConvertRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ConvertRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConvertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Result        float64                `protobuf:"fixed64,4,opt,name=result,proto3" json:"result,omitempty"`
	Rate          float64                `protobuf:"fixed64,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertResponse) Reset() {
	*x = ConvertResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertResponse) ProtoMessage() {}

func (x *ConvertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertResponse.ProtoReflect.Descriptor instead.
func (*ConvertResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *ConvertResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ConvertResponse) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ConvertResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertResponse) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *ConvertResponse) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ConvertResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ConvertBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertBatchRequest) Reset() {
	*x = ConvertBatchRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertBatchRequest) ProtoMessage() {}

func (x *ConvertBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertBatchRequest.ProtoReflect.Descriptor instead.
func (*ConvertBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertBatchRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ConvertBatchRequest) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ConvertBatchRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ConvertBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Results       map[string]float64     `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertBatchResponse) Reset() {
	*x = ConvertBatchResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertBatchResponse) ProtoMessage() {}

func (x *ConvertBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertBatchResponse.ProtoReflect.Descriptor instead.
func (*ConvertBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertBatchResponse) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ConvertBatchResponse) GetResults() map[string]float64 {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ConvertBatchResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertBatchResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type GetTransactionUSDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionUSDRequest) Reset() {
	*x = GetTransactionUSDRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionUSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionUSDRequest) ProtoMessage() {}

func (x *GetTransactionUSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionUSDRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionUSDRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{6}
}

func (x *GetTransactionUSDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTransactionUSDResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionId    int64                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	AmountUsd        float64                `protobuf:"fixed64,2,opt,name=amount_usd,json=amountUsd,proto3" json:"amount_usd,omitempty"`
	OriginalAmount   float64                `protobuf:"fixed64,3,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	OriginalCurrency string                 `protobuf:"bytes,4,opt,name=original_currency,json=originalCurrency,proto3" json:"original_currency,omitempty"`
	ConvertedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=converted_at,json=convertedAt,proto3" json:"converted_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTransactionUSDResponse) Reset() {
	*x = GetTransactionUSDResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionUSDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionUSDResponse) ProtoMessage() {}

func (x *GetTransactionUSDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionUSDResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionUSDResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionUSDResponse) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *GetTransactionUSDResponse) GetAmountUsd() float64 {
	if x != nil {
		return x.AmountUsd
	}
	return 0
}

func (x *GetTransactionUSDResponse) GetOriginalAmount() float64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *GetTransactionUSDResponse) GetOriginalCurrency() string {
	if x != nil {
		return x.OriginalCurrency
	}
	return ""
}

func (x *GetTransactionUSDResponse) GetConvertedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ConvertedAt
	}
	return nil
}

var File_proto_currency_currency_proto protoreflect.FileDescriptor

const file_proto_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/currency/currency.proto\x12\bcurrency\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"%\n" +
	"\x0fGetRatesRequest\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\"\xd7\x01\n" +
	"\x10GetRatesResponse\x12\x12\n" +
	"\x04base\x18\x01 \x01(\tR\x04base\x12;\n" +
	"\x05rates\x18\x02 \x03(\v2%.currency.GetRatesResponse.RatesEntryR\x05rates\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"L\n" +
	"\x0eConvertRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xb3\x01\n" +
	"\x0fConvertResponse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06result\x18\x04 \x01(\x01R\x06result\x12\x12\n" +
	"\x04rate\x18\x05 \x01(\x01R\x04rate\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Q\n" +
	"\x13ConvertBatchRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x03(\tR\x02to\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xff\x01\n" +
	"\x14ConvertBatchResponse\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12E\n" +
	"\aresults\x18\x02 \x03(\v2+.currency.ConvertBatchResponse.ResultsEntryR\aresults\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a:\n" +
	"\fResultsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"*\n" +
	"\x18GetTransactionUSDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xf6\x01\n" +
	"\x19GetTransactionUSDResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x03R\rtransactionId\x12\x1d\n" +
	"\n" +
	"amount_usd\x18\x02 \x01(\x01R\tamountUsd\x12'\n" +
	"\x0foriginal_amount\x18\x03 \x01(\x01R\x0eoriginalAmount\x12+\n" +
	"\x11original_currency\x18\x04 \x01(\tR\x10originalCurrency\x12=\n" +
	"\fconverted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vconvertedAt2\xde\x03\n" +
	"\x0fCurrencyService\x12b\n" +
	"\bGetRates\x12\x19.currency.GetRatesRequest\x1a\x1a.currency.GetRatesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/currency/{base}\x12c\n" +
	"\aConvert\x12\x18.currency.ConvertRequest\x1a\x19.currency.ConvertResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/currency/convert\x12x\n" +
	"\fConvertBatch\x12\x1d.currency.ConvertBatchRequest\x1a\x1e.currency.ConvertBatchResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/api/v1/currency/convert/batch\x12\x87\x01\n" +
	"\x11GetTransactionUSD\x12\".currency.GetTransactionUSDRequest\x1a#.currency.GetTransactionUSDResponse\")\x82\xd3\xe4\x93\x02#\x12!/api/v1/currency/transaction/{id}B\fZ\n" +
	"./currencyb\x06proto3"

var (
	file_proto_currency_currency_proto_rawDescOnce sync.Once
	file_proto_currency_currency_proto_rawDescData []byte
)

func file_proto_currency_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)))
	})
	return file_proto_currency_currency_proto_rawDescData
}

var file_proto_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_currency_currency_proto_goTypes = []any{
	(*GetRatesRequest)(nil),           // 0: currency.GetRatesRequest
	(*GetRatesResponse)(nil),          // 1: currency.GetRatesResponse
	(*ConvertRequest)(nil),            // 2: currency.ConvertRequest
	(*ConvertResponse)(nil),           // 3: currency.ConvertResponse
	(*ConvertBatchRequest)(nil),       // 4: currency.ConvertBatchRequest
	(*ConvertBatchResponse)(nil),      // 5: currency.ConvertBatchResponse
	(*GetTransactionUSDRequest)(nil),  // 6: currency.GetTransactionUSDRequest
	(*GetTransactionUSDResponse)(nil), // 7: currency.GetTransactionUSDResponse
	nil,                               // 8: currency.GetRatesResponse.RatesEntry
	nil,                               // 9: currency.ConvertBatchResponse.ResultsEntry
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
}
var file_proto_currency_currency_proto_depIdxs = []int32{
	8,  // 0: currency.GetRatesResponse.rates:type_name -> currency.GetRatesResponse.RatesEntry
	10, // 1: currency.GetRatesResponse.timestamp:type_name -> google.protobuf.Timestamp
	10, // 2: currency.ConvertResponse.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 3: currency.ConvertBatchResponse.results:type_name -> currency.ConvertBatchResponse.ResultsEntry
	10, // 4: currency.ConvertBatchResponse.timestamp:type_name -> google.protobuf.Timestamp
	10, // 5: currency.GetTransactionUSDResponse.converted_at:type_name -> google.protobuf.Timestamp
	0,  // 6: currency.CurrencyService.GetRates:input_type -> currency.GetRatesRequest
	2,  // 7: currency.CurrencyService.Convert:input_type -> currency.ConvertRequest
	4,  // 8: currency.CurrencyService.ConvertBatch:input_type -> currency.ConvertBatchRequest
	6,  // 9: currency.CurrencyService.GetTransactionUSD:input_type -> currency.GetTransactionUSDRequest
	1,  // 10: currency.CurrencyService.GetRates:output_type -> currency.GetRatesResponse
	3,  // 11: currency.CurrencyService.Convert:output_type -> currency.ConvertResponse
	5,  // 12: currency.CurrencyService.ConvertBatch:output_type -> currency.ConvertBatchResponse
	7,  // 13: currency.CurrencyService.GetTransactionUSD:output_type -> currency.GetTransactionUSDResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_currency_currency_proto_init() }
func file_proto_currency_currency_proto_init() {
	if File_proto_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_currency_proto_depIdxs,
		MessageInfos:      file_proto_currency_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_currency_proto = out.File
	file_proto_currency_currency_proto_goTypes = nil
	file_proto_currency_currency_proto_depIdxs = nil
}
